import { workflowResumeFlow } from "./workflow-resume-flow";
import { importFlow } from "./import-flow";
import { expect, test } from "@playwright/test";
test("setup, codes, sign-in, invitation, recovery and access protection", async ({ page, request, browser }, testInfo) => {
  test.setTimeout(120_000);
  expect((await request.post("/api/identity/setup", { data: {} })).status()).toBe(403);
  expect((await request.get("/dashboard", { maxRedirects: 0 })).status()).toBe(307);
  expect((await request.post("/api/identity/setup", { headers: { origin: "http://127.0.0.1:3102" }, data: { padding: "x".repeat(33000) } })).status()).toBe(413);
  expect((await request.get("/api/auth/csrf", { headers: { host: "untrusted.example.test" } })).status()).toBe(403);
  await page.goto("/setup");
  await page.getByLabel("Setup code", { exact: true }).fill("synthetic-browser-bootstrap-secret-for-tests-only");
  await page.getByLabel("Your name").fill("Synthetic owner");
  await page.getByLabel("Email", { exact: true }).fill("owner@example.test");
  await page.getByLabel("Password", { exact: true }).fill("synthetic owner password");
  await page.getByLabel("Confirm password").fill("synthetic owner password");
  await page.screenshot({ path: testInfo.outputPath("setup-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "Create owner account" }).click();
  await expect(page.getByRole("heading", { name: "Save your recovery codes" })).toBeVisible();
  const code = await page.locator(".recovery-codes code").first().textContent();
  await expect(page.getByRole("button", { name: "Continue to sign in" })).toBeDisabled();
  await page.getByLabel("I have saved my recovery codes").check();
  await page.getByRole("link", { name: "Continue to sign in" }).click();
  await page.getByLabel("Email", { exact: true }).fill("owner@example.test");
  await page.getByLabel("Password", { exact: true }).fill("synthetic owner password");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await expect(page.getByText("No published report yet")).toBeVisible();
  const session = await page.request.get("/api/auth/session");
  expect(await session.text()).not.toMatch(/sid|reference|tokenHash/);
  expect((await page.request.post("/api/workflows/resume", { headers: { origin: "http://127.0.0.1:3102" }, data: { runId: "00000000-0000-4000-8000-000000000001" } })).status()).toBe(403);
  await importFlow(page, testInfo);
  await page.goto("/setup");
  await expect(page).toHaveURL(/\/dashboard\/settings$/);
  const cookies = await page.context().cookies();
  const cookie = cookies.find(value => value.name === "authjs.session-token");
  expect(cookie?.httpOnly).toBe(true); expect(cookie?.sameSite).toBe("Lax");
  await page.goto("/dashboard/settings");
  await page.getByLabel("Current password").fill("synthetic owner password");
  await page.getByRole("button", { name: "Confirm password", exact: true }).click();
  await expect(page.getByText("Password confirmed for five minutes.")).toBeVisible();
  await workflowResumeFlow(page);
  await page.getByLabel("Member email").fill("viewer@example.test");
  await page.getByRole("button", { name: "Create invitation" }).click();
  await expect(page.locator(".private-link")).toBeVisible();
  const link = await page.locator(".private-link").textContent();
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } }); const guest = await context.newPage();
  await guest.goto(link!);
  await guest.getByLabel("Your name").fill("Synthetic viewer");
  await guest.getByLabel("Email", { exact: true }).fill("viewer@example.test");
  await guest.getByLabel("Password", { exact: true }).fill("synthetic viewer password");
  await guest.getByLabel("Confirm password").fill("synthetic viewer password");
  await guest.screenshot({ path: testInfo.outputPath("invite-mobile.png"), fullPage: true });
  expect(await guest.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await guest.getByRole("button", { name: "Join household" }).click();
  await expect(guest.getByRole("heading", { name: "Save your recovery codes" })).toBeVisible();
  await guest.getByLabel("I have saved my recovery codes").check();
  await guest.getByRole("link", { name: "Continue to sign in" }).click();
  await guest.getByLabel("Email", { exact: true }).fill("viewer@example.test");
  await guest.getByLabel("Password", { exact: true }).fill("synthetic viewer password");
  await guest.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(guest).toHaveURL(/\/dashboard$/);
  await guest.goto("/dashboard/settings");
  await expect(guest.getByRole("heading", { name: "Invite a member" })).toHaveCount(0);
  await guest.screenshot({ path: testInfo.outputPath("settings-mobile.png"), fullPage: true });
  const forbidden = await guest.request.post("/api/identity/invite", { headers: { origin: "http://127.0.0.1:3102" }, data: { email: "another@example.test", role: "viewer" } });
  expect(forbidden.status()).toBe(403);
  expect((await guest.request.post("/api/workflows/resume", { headers: { origin: "http://127.0.0.1:3102" }, data: { runId: "00000000-0000-4000-8000-000000000001" } })).status()).toBe(403);
  expect((await guest.request.post("/api/imports/confirm", { headers: { origin: "http://127.0.0.1:3102" }, data: {} })).status()).toBe(403);
  await guest.goto("/dashboard/imports");
  await expect(guest.getByText("You have view access.", { exact: false })).toBeVisible();
  await expect(guest.getByRole("button", { name: "Confirm and save batch" })).toHaveCount(0);
  await guest.goto("/recover");
  await guest.getByLabel("Email", { exact: true }).fill("owner@example.test");
  await guest.getByLabel("Recovery code", { exact: false }).fill(code!);
  await guest.getByLabel("New password", { exact: true }).fill("replacement owner password");
  await guest.getByLabel("Confirm password").fill("replacement owner password");
  await guest.getByRole("button", { name: "Reset password" }).click();
  await expect(guest.getByText("Your password has been updated.", { exact: false })).toBeVisible();
  await page.goto("/dashboard"); await expect(page).toHaveURL(/\/login$/);
  await context.close();
});
