import { expect, type Page, type TestInfo } from "@playwright/test";
import { Pool } from "pg";
import { readFileSync } from "node:fs";
import { parseEnv } from "node:util";
import { drizzle } from "drizzle-orm/node-postgres";
import { acceptDelivery } from "@/db/workflows/dispatch";
import { beginCalculationPlan, advanceCalculationPlan } from "@/db/workflows/planning";
import { beginBankCandidate, advanceBankCandidate } from "@/db/calculations/bank-worker";
import { advanceBalanceCandidate } from "@/db/calculations/bank-balance-worker";
import { publishBankRelease } from "@/db/calculations/publish";
export async function importFlow(page: Page, info: TestInfo) {
  page.setDefaultTimeout(15_000);
  const raw = process.env.TEST_DATABASE_URL ?? parseEnv(readFileSync(".env.local", "utf8")).TEST_DATABASE_URL;
  const url = new URL(raw!);
  if (process.env.VERCEL || !["localhost", "127.0.0.1", "[::1]"].includes(url.hostname) || url.pathname !== "/networth_test") throw new Error("Use only the disposable browser test database.");
  const db = new Pool({ connectionString: raw });
  let worker: Pool | undefined;
  const header = readFileSync("public/templates/bank-v1.csv", "utf8").trim();
  const csv = `${header}\nbank-v1,one,SYNTHETIC-1,2026-09-01,Synthetic cinema,debit,100.00,INR,expense,,,,\n`;
  try {
    await page.goto("/dashboard/imports");
    await expect(page.getByText("Confirmation paused.", { exact: false }).first()).toBeVisible();
    await page.getByLabel("New account name", { exact: true }).fill("Synthetic browser bank");
    await page.getByLabel("Bank-v1 CSV", { exact: true }).setInputFiles({ name: "synthetic.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
    await page.getByLabel("Opening balance (blank = unknown)").fill("200");
    await page.getByLabel("Closing balance (blank = unknown)").fill("100");
    await page.getByRole("button", { name: "Check statement for review" }).click();
    await expect(page.getByText("I acknowledge: Some income", { exact: false })).toBeVisible();
    await expect(page.getByRole("button", { name: "Confirm and save batch" })).toBeDisabled();
    expect((await db.query("select count(*)::int n from core.import_batch")).rows[0].n).toBe(0);
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: info.outputPath("import-review-desktop.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: info.outputPath("import-review-mobile.png"), fullPage: true });
    const dimensions = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, overflow: Array.from(document.querySelectorAll(".import-fields, .import-fields input, .import-fields select, .import-workspace > *, .import-table-scroll")).map(el => ({ tag: el.tagName, cls: el.className, right: el.getBoundingClientRect().right, width: el.getBoundingClientRect().width })).filter(el => el.right > innerWidth) }));
    expect(dimensions.scrollWidth, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole("button", { name: "Cancel preview" }).click();
    expect((await db.query("select count(*)::int n from core.dim_account")).rows[0].n).toBe(0);
    // The test verifier attests capacity directly; production has no HTTP/UI bypass.
    await db.query("insert into ops.import_admission values(true,now()+interval '1 hour',true,100,300000000,'Synthetic test verification')");
    await page.getByRole("button", { name: "Refresh status" }).click();
    await page.getByLabel("New account name", { exact: true }).fill("Synthetic browser bank");
    await page.getByLabel("Bank-v1 CSV", { exact: true }).setInputFiles({ name: "synthetic.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
    await page.getByLabel("Opening balance (blank = unknown)").fill("200");
    await page.getByLabel("Closing balance (blank = unknown)").fill("100");
    await page.getByRole("button", { name: "Check statement for review" }).click();
    await expect(page.getByRole("button", { name: "Confirm and save batch" })).toBeDisabled();
    const warning = page.getByRole("checkbox", { name: "I acknowledge: Some income or expenses will remain Uncategorized." });
    await warning.focus(); await page.keyboard.press("Space");
    await expect(warning).toBeChecked();
    await expect(page.getByRole("button", { name: "Confirm and save batch" })).toBeEnabled();
    await page.getByLabel("Select row one", { exact: true }).check();
    await page.getByRole("combobox", { name: "Bulk category", exact: true }).selectOption("entertainment");
    await page.getByRole("button", { name: "Apply to 1 selected" }).click();
    await expect(page.getByRole("combobox", { name: "Category for row one", exact: true })).toHaveValue("entertainment");
    await page.getByRole("button", { name: "Check statement for review" }).click();
    await expect(page.getByRole("button", { name: "Confirm and save batch" })).toBeEnabled();
    await page.getByRole("button", { name: "Confirm and save batch" }).click();
    await expect(page.getByText(/saved at revision 1/)).toBeVisible();
    expect((await db.query("select c.code from core.fact_posting p join core.dim_category c on c.id=p.category_id")).rows).toEqual([{ code: "entertainment" }]);
    expect((await db.query("select count(*)::int n from core.source_record")).rows[0].n).toBe(3);
    await db.query("do $$ begin if not exists(select from pg_roles where rolname='networth_test_worker') then create role networth_test_worker login password 'synthetic-worker-test-only' noinherit nosuperuser nocreatedb nocreaterole nobypassrls; end if; end $$");
    await db.query("grant networth_worker to networth_test_worker with inherit false");
    await db.query("insert into ops.execution_capacity values(true,now()+interval '1 hour',100,300000000)");
    const workerUrl = new URL(raw!); workerUrl.username = "networth_test_worker"; workerUrl.password = "synthetic-worker-test-only";
    worker = new Pool({ connectionString: workerUrl.toString(), max: 2 }); const workerDb = drizzle(worker);
    const intent = (await db.query(`select o.id as "outboxId",o.household_id as "householdId",o.batch_id as "batchId",o.revision from ops.outbox_event o order by o.revision desc limit 1`)).rows[0];
    await acceptDelivery(intent, workerDb);
    let plan = await beginCalculationPlan(intent, workerDb);
    while (plan.state !== "prepared") plan = await advanceCalculationPlan({ runId: plan.id, householdId: intent.householdId, page: plan.page }, workerDb);
    let bank = await beginBankCandidate({ runId: plan.id, householdId: intent.householdId, asOf: "2026-09-01" }, workerDb);
    while (bank.state !== "calculated") bank = await advanceBankCandidate({ runId: plan.id, householdId: intent.householdId, page: bank.page }, workerDb);
    let balance = await advanceBalanceCandidate({ runId: plan.id, householdId: intent.householdId, page: 0 }, workerDb);
    while (balance.state !== "calculated") balance = await advanceBalanceCandidate({ runId: plan.id, householdId: intent.householdId, page: balance.page }, workerDb);
    const releaseId = await publishBankRelease({ runId: plan.id, householdId: intent.householdId }, workerDb);
    expect(releaseId).toBeTruthy();
    const reportResponse = await page.request.get("/api/reports/overview?month=2026-09");
    expect(reportResponse.status()).toBe(200);
    expect(await reportResponse.json()).toMatchObject({ release: { id: releaseId }, summary: { monthlyExpenseInr: "100.000000000000" } });
    await page.goto("/dashboard");
    await expect(page.getByText("Synthetic browser bank")).toBeVisible();
    await expect(page.getByText("Entertainment", { exact: true })).toBeVisible();
    await expect(page.getByText("Incomplete data", { exact: true })).toBeVisible();
    const sourceDisclosure = page.locator(".activity-list details").first();
    await sourceDisclosure.locator("summary").click();
    await expect(sourceDisclosure.getByText("Import revision", { exact: true })).toBeVisible();
    await expect(sourceDisclosure.getByText("Source row 1", { exact: true })).toBeVisible();
    await sourceDisclosure.locator("summary").click();
    await page.getByRole("button", { name: "Select reporting month, September 2026" }).click();
    await page.getByRole("button", { name: "Aug", exact: true }).click();
    await expect(page.getByText("No category activity", { exact: true })).toBeVisible();
    await expect(page.getByText("No activity this month", { exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Select reporting month, August 2026" }).click();
    await page.getByRole("button", { name: "Sep", exact: true }).click();
    await expect(page.getByText("Entertainment", { exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath("published-report-desktop.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: info.outputPath("published-report-mobile.png"), fullPage: true });
    const reportDimensions = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth,
      overflow: Array.from(document.querySelectorAll("body *")).map(element => { const box = element.getBoundingClientRect(); return { tag: element.tagName, cls: element.className, left: box.left, right: box.right, width: box.width, ownScroll: element.scrollWidth, ownClient: element.clientWidth }; })
        .filter(element => element.right > innerWidth + 1 || element.left < -1).slice(0, 20) }));
    expect(reportDimensions.scrollWidth, JSON.stringify(reportDimensions)).toBeLessThanOrEqual(reportDimensions.width);
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole("link", { name: "Open activity" }).click();
    await expect(page.getByRole("heading", { name: "Activity", exact: true })).toBeVisible();
    await expect(page.getByText("Synthetic cinema", { exact: true })).toBeVisible();
    await page.locator(".activity-list details summary").first().click();
    await expect(page.getByText("Import revision", { exact: true })).toBeVisible();
    const oversized = await page.request.post("/api/imports/confirm", { headers: { origin: "http://127.0.0.1:3102" }, data: { padding: "₹".repeat(1_000_001) } });
    expect(oversized.status()).toBe(413);
    const bad = await page.request.post("/api/imports/review", { headers: { origin: "http://127.0.0.1:3102" }, data: {} });
    expect(bad.status()).toBe(400);
  } finally { await worker?.end(); await db.end(); }
}
