export const DEPLOYMENT_CONFIG_FILE = ".env.deploy.local";
export const RUNTIME_ROLE = "networth_app";
export const WORKER_ROLE = "networth_jobs";

export type DeploymentSecrets = {
  databaseAdminUrl: string;
  runtimePassword: string;
  workerPassword: string;
  authSecret: string;
  bootstrapSecret: string;
  cronSecret: string;
  appUrl: string;
};

export type CapacityPresetName = keyof typeof CAPACITY_PRESETS;

export const CAPACITY_PRESETS = {
  personal: {
    imports: 10,
    attempts: 500,
    storageBytes: 100_000_000,
    minutes: 1_440,
    description: "Occasional imports for one household",
  },
  regular: {
    imports: 30,
    attempts: 1_500,
    storageBytes: 200_000_000,
    minutes: 1_440,
    description: "Regular imports across several bank accounts",
  },
} as const;

export function productionOrigin(raw: string) {
  const url = new URL(raw.trim());
  if (url.protocol !== "https:" || url.username || url.password || url.search || url.hash || url.pathname !== "/") {
    throw new Error("Use the exact HTTPS app origin without a path, query, credentials or fragment.");
  }
  return url.origin;
}

export function hostedDatabaseUrl(raw: string) {
  const url = new URL(raw.trim());
  if (!["postgres:", "postgresql:"].includes(url.protocol) || !url.hostname || !url.username || !url.password) {
    throw new Error("Use a complete Postgres connection URL with a database username and password.");
  }
  url.searchParams.set("sslmode", "verify-full");
  return url.toString();
}

export function connectionForRole(adminUrl: string, role: string, password: string) {
  const url = new URL(hostedDatabaseUrl(adminUrl));
  url.username = role;
  url.password = password;
  return url.toString();
}

function envLine(key: string, value: string) {
  if (/[\r\n]/u.test(value)) throw new Error("Deployment values cannot contain newlines.");
  return `${key}=${JSON.stringify(value)}`;
}

export function deploymentEnvironment(input: DeploymentSecrets) {
  const admin = hostedDatabaseUrl(input.databaseAdminUrl);
  const appUrl = productionOrigin(input.appUrl);
  return [
    "# Generated by npm run deploy:prepare. Keep this file private and never commit it.",
    "# Add these values to the Vercel Production environment.",
    envLine("DATABASE_URL", connectionForRole(admin, RUNTIME_ROLE, input.runtimePassword)),
    envLine("DATABASE_ADMIN_URL", admin),
    envLine("DATABASE_WORKER_URL", connectionForRole(admin, WORKER_ROLE, input.workerPassword)),
    envLine("AUTH_SECRET", input.authSecret),
    envLine("BOOTSTRAP_SECRET", input.bootstrapSecret),
    envLine("CRON_SECRET", input.cronSecret),
    envLine("APP_URL", appUrl),
    "",
    "# The official Inngest Vercel integration adds these to Vercel.",
    "INNGEST_EVENT_KEY=",
    "INNGEST_SIGNING_KEY=",
    "INNGEST_SIGNING_KEY_FALLBACK=",
    "",
  ].join("\n");
}

export function capacityPreset(raw: string | undefined) {
  if (raw === "personal" || raw === "regular") return { name: raw, ...CAPACITY_PRESETS[raw] };
  throw new Error("Choose a capacity preset: personal or regular.");
}
